# Generated by Django 3.1.7 on 2021-03-08 04:02

from django.db import migrations, models
import posts.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=65536)),
                ('note_hash', models.CharField(max_length=20)),
                ('shared', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(models.Model, posts.mixins.CreatedAgoMixin),
        ),
    ]
