# Generated by Django 3.1.7 on 2021-03-08 04:02

from django.db import migrations, models
import posts.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=65536)),
                ('replace', models.BooleanField(default=True)),
                ('shared', models.BooleanField(default=True)),
                ('starred', models.BooleanField(default=False)),
                ('toread', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(models.Model, posts.mixins.CreatedAgoMixin),
        ),
    ]
